### ISSUE TITLE
Create test cases for copy method

### ISSUE THREAD

**Issue by LeeBadal** [heeenkie/teammates#6]
Tests relating to the frontend, i.e. not e2e testing.

**Comment by heeenkie** [comment]
src -> web -> app -> components -> copy-session-modal- > copy-**course**-modal.component.spec.ts

src -> web -> app -> components -> copy-session-modal- > copy-**sessions**-modal.component.spec.ts

**Comment by LeeBadal** [comment]
REQUIREMENTS:
1. Change the course ID
2. Copy all the course’s sessions, including questions but not responses
3. Remove all students
4. Create new start/end dates

**Comment by LeeBadal** [comment]
Needs review: @MatildaAR @heeenkie 

COMMIT:  https://github.com/heeenkie/teammates/commit/c042e60c7d345200f2b3f2bc51879c00d37aa1af

Tests the copy button if disabled/active and creates new snapshot
